TÓPICOS EM INTELIGÊNCIA COMPUTACIONAL - PROGRAMA DE PÓS-GRADUAÇÃO EM MODELAGEM COMPUTACIONAL DE SISTEMAS - 2021-2

<img src="imagens/ppgmcs.png" alt="tic">

---
# Univerisdade Federal do Tocantins - UFT
## Programa de Pós-graduação em Modelagem Computacional de Sistemas - PPGMCS

---
# Tópicos em Inteligência Computacional 2021-2
### Professor: Marcelo Lisboa. <mlisboa@uft.edu.br>

# Módulo 02 - NumPy

> Em DataScience (DS) devem ser manipulados e transformados dados diversos quanto ao tipo e à origem. O armazenamento e manipulação eficiente de matrizes numéricas é absolutamente fundamental para fazer ciência de dados. 

> Nessa perspectiva será feita uma revisão especial das ferramentas personalizadas que o Python possui para lidar com matrizes numéricas: Os pacotes NumPy (Módulo 02) e Pandas (Módulo 03).

> A biblioteca NumPy (abreviação de Python Numérico) fornece uma interface eficiente para armazenar e operar em buffers de dados densos. As matrizes NumPy são como o tipo *‘list’* do Python, no entanto, as matrizes NumPy fornecem um armazenamento mais eficiente e operações com dados à medida que as matrizes aumentam de tamanho. 

> As matrizes NumPy formam o **núcleo** de quase todo o **ecossistema** de ferramentas de DS em Python. Logo, saber lidar e usar o NumPy de forma eficaz será de grande importância para quem pretende lidar com DS nas mas diversas áreas de aplicação.

> Maiores informações podem ser encontrada em https://numpy.org/

## Importando a biblioteca NumPy

In [1]:
# importando a biblioteca numpy
import numpy as np

In [2]:
# verficando a versão da biblioteca numpy
np.__version__

'1.19.5'

In [3]:
# help
np?

## Listas em Numpy

In [4]:
# exemplo numpy-01
# criando uma lista de inteiros
L = list(range(10))
print('L = ',L)

L =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
# exemplo numpy-02
# verificando o tipo
type(L[0])

int

In [6]:
# exemplo numpy-03
# criando uma lista de strings
L1 =[str(c) for c in L]
L1

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
# exemplo numpy-04
# Verificando o tipo da string
type(L1[0])

str

In [8]:
# exemplo numpy-05
# criando lista heterogénea
L2 = [False, "J", '2', 3.0, 0, 2-4j]
L3 = [type(item) for item in L2]
print('LH : ',L3)

LH :  [<class 'bool'>, <class 'str'>, <class 'str'>, <class 'float'>, <class 'int'>, <class 'complex'>]


## Arrays de Tipo Fixo
Python oferece diversas opções para armazenar dados de forma eficiente, buffers de dados de tipo fixo. O módulo **array** (python >= 3.3) pode ser usado para criar arrays densos de tipo uniforme.

In [9]:
# exemplo numpy-06
# criando array de tipo fixo
import array 
L4 = list(range(10))
A = array.array('i',L4)
print('A : ',A)

A :  array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


No exemplo numpy-06, o índice **'i'** indica que o conteúdo é de inteiros. Se dos dados foram reais?, booleanos?, etc.

## Criando Listas de Listas Python

In [10]:
# exemplo numpy-07
# criando um array de inteiros
I = np.array([1, 3, 5, 7, 9, 0])
print('I : ',I)

I :  [1 3 5 7 9 0]


In [11]:
# exemplo numpy-08
# criando uma array de mixto
M = np.array([1.0, 3.5, 5, 7, 9, 0])
print('M : ',M)

M :  [1.  3.5 5.  7.  9.  0. ]


In [12]:
# exemplo numpy-09
# Fixar o tipo de dados de uma array
I1 = np.array([1, 3, 5, 7, 9, 0], dtype='float32')
print("I : ",I1)

I :  [1. 3. 5. 7. 9. 0.]


In [13]:
# exemplo numpy-10
# criando um array multidimensional
M1 = np.array([range(i, i + 3) for i in [2, 4, 6]])
print('Multidimensional : ',M1)

Multidimensional :  [[2 3 4]
 [4 5 6]
 [6 7 8]]


## Criando Arrays de Zero

In [14]:
# exemplo numpy-11
# criando um array de zeros
Z = np.zeros(10, dtype=int)
print(Z)
print("tamanho do vetor Z=",len(Z))

[0 0 0 0 0 0 0 0 0 0]
tamanho do vetor Z= 10


In [15]:
# exemplo numpy-12
# criando uma array de 3x5 de dados de tipo real (float)
U = np.ones((3,5), dtype=float)
U

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# exemplo numpy-13
# criando uma array de 3x5 de dados com 3.14
U1 = np.full((3,5), 3.14)
U1

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
# exemplo numpy-14
# criar uma array com valores de uma sequência linear de 0 a 20
# com incremento (paso) 2.
Ar = np.arange(0,20,2)
Ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# exemplo numpy-15
# criar uma array de 5 valores espaciados entre 0 e 1.
lin = np.linspace(0,1,5)
print('L : ',lin)

L :  [0.   0.25 0.5  0.75 1.  ]


In [19]:
# exemplo numpy-16
# criar uma array 4x7 de distribuição uniforme (0,1)
R = np.random.random((4,7))
R

array([[0.23342388, 0.64576118, 0.26226328, 0.70417851, 0.65858496,
        0.51958143, 0.70019161],
       [0.4506861 , 0.27073438, 0.1683649 , 0.36489883, 0.76781943,
        0.34032013, 0.97455169],
       [0.1136125 , 0.71229558, 0.43007735, 0.08317934, 0.02774848,
        0.73947851, 0.56150233],
       [0.05019938, 0.55057575, 0.79526842, 0.6350528 , 0.11833491,
        0.03830087, 0.62554687]])

In [20]:
# exemplo numpy-17
# criar uma array 5x5 de distribuição normal com valores aleatórios
# com media 0 e desvio padrão 1.
R1 = np.random.normal(0,1,(5,5))
R1

array([[ 0.39745738,  0.4143695 , -1.13600609,  0.02313077, -0.38745117],
       [ 0.133222  ,  0.5756032 ,  0.70208228, -0.83325873, -1.06332077],
       [-0.23537741, -0.27108017, -1.11272407,  0.50688984, -0.41355309],
       [ 0.07618584, -0.77098071, -0.52744243,  0.9731167 ,  0.2143356 ],
       [-1.03428048, -0.30896159,  0.22740676, -0.52353367,  0.08456091]])

In [21]:
# exemplo numpy-18
# criar uma array 4x4 de inteiros aleatórios no intervalo [0,5]
R2 = np.random.randint(0,5,(4,4))
R2

array([[1, 3, 2, 3],
       [4, 0, 1, 2],
       [0, 1, 1, 0],
       [4, 4, 0, 2]])

In [22]:
# exemplo numpy-19
# criar uma matriz identidade de 5x5
Mi = np.eye(5)
Mi

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Tipos de Dados Padrão no NumPy

In [23]:
# exemplo numpy-20
# Array de zeros
T1 = np.zeros(8,dtype='int16')
T1

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [24]:
# exemplo numpy-21
# Array de zeros
T2 = np.zeros(8,dtype=np.int16)
T2

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Os diversos tipos de dados padrão NumPy podem ser encontrados em https://numpy.org/devdocs/user/basics.types.html

## Noções Básicas de Arrays (matrizes) NumPy
Manipulação de matrizes NumPy para acessar dados e sub-matrizes, para dividir, redimensionar e unir matrizes.

### Atributos de Matrizes NumPy

In [25]:
# exemplo numpy-22
# Atributos: ndim, shape, size.
x1 = np.random.randint(10, size=5) # 1-D
x2 = np.random.randint(10, size=(4, 5)) # 2-D
x3 = np.random.randint(10, size=(3, 5, 6)) # 3-D
print("x1 : ", x1)
print("x2 : ", x2)
print("x3 : ", x3)
# atributos: ndim (numero de dim), shape (tamanho de cada dimensões), 
# size (tamanho total da matriz)
print("x3 ndim : ", x3.ndim)
print("x3 shape : ", x3.shape)
print("x3 size : ", x3.size)

x1 :  [0 1 0 3 5]
x2 :  [[3 4 9 8 0]
 [5 3 7 6 8]
 [6 2 4 9 1]
 [7 8 1 4 2]]
x3 :  [[[3 0 1 6 4 3]
  [7 6 4 7 7 4]
  [5 6 1 7 7 2]
  [5 0 8 5 6 5]
  [9 7 0 9 9 0]]

 [[5 1 6 1 6 0]
  [9 6 3 7 9 2]
  [6 1 4 1 2 1]
  [9 5 9 3 8 4]
  [4 1 5 0 1 3]]

 [[7 5 5 3 2 6]
  [5 5 4 7 4 2]
  [0 6 4 7 2 0]
  [2 3 4 8 7 7]
  [1 8 3 8 9 7]]]
x3 ndim :  3
x3 shape :  (3, 5, 6)
x3 size :  90


In [26]:
# exemplo numpy-23
# atributo : dtype
print("dtype:", x3.dtype)

dtype: int32


In [27]:
# exemplo numpy-24
# atributos : itemsize e nbytes (itemsize = nbytes!!!)
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes:  360 bytes


### Indexação de Matrizes: Acessando Elementos Simples

In [28]:
# exemplo numpy-25
# Usando índice para acessar elementos da array: array[indice]
elemento = x1[0] 
print('Elementos : ',elemento)

Elementos :  0


In [29]:
# exemplo numpy-26
# Para indexar a partir do final da matriz, se pode usar índices negativos.
N = np.array([0, 1, 2, 3, 4, 5])
N1 = N[-1]
print(N1)

5


In [30]:
# exemplo numpy-27
# acessar elementos de uma array multidimensional [i,j], i,j = 0..N
print('D : ',x2.shape)
print('x1[2,2] = ',x2[2,2]) # elemento na linha = 2 e coluna = 2

D :  (4, 5)
x1[2,2] =  4


In [31]:
# exemplo numpy-28
# mudando um elemento de uma matriz
Mat = np.array([[0,1,2,3],[4, 5, 6, 7],[8, 9, 10,11]])
# dimensão da matriz
Dim = print('D: ',Mat.shape)
# mudando um elemento
Mat[2,2]= -1
print(Mat)

D:  (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 -1 11]]


### Fatiar Matrizes. Acessando Submatrizes
A sintaxe para dividir uma matriz NumPy segue o padrão de uma lista em Python. Para acessar uma  divisão ou fatia ou parte de uma matriz (submatriz) X, usa-se a seguinte sintaxe:

**X[inicio:fim:paso]** ou **X[start:stop:step]**

In [32]:
# exemplo numpy-29
# uma submatriz unidimensional
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# exemplo numpy-30
# os 4 elementos iniciais
x4 = X[:4]
print(x4)

[0 1 2 3]


In [34]:
# exemplo numpy-31
# Os elementos depois do índice 5
x5 = X[5:]
print(x5)

[5 6 7 8 9]


In [35]:
# exemplo numpy-32
# subarray media
med = X[3:7]
print(med)

[3 4 5 6]


In [36]:
# exemplo numpy-33
# Qualquer outro elemento
Q1 = X[::2]
print(Q1)

[0 2 4 6 8]


In [37]:
# exemplo numpy-34
# Qualquer outro elemento, iniciando em 1
Q2 = X[1::2]
print(Q2)

[1 3 5 7 9]


In [38]:
# exemplo numpy-35
# step = paso = negativo = -1: reverso
N1 = X[::-1]
print(N1)

[9 8 7 6 5 4 3 2 1 0]


In [39]:
# exemplo numpy-36
# reversa cada elemento a partir do indice 5
N2 = X[5::-2]
print(N2)

[5 3 1]


### SubMatrizes Multidimensionais

In [40]:
# exemplo numpy-37
# Matriz multidimensional
Mul = np.array([[12, 8, 4, 0],[5, 4, 3, 2],[3, 3, 2, 1]])
Mul

array([[12,  8,  4,  0],
       [ 5,  4,  3,  2],
       [ 3,  3,  2,  1]])

In [41]:
# exemplo numpy-38
# dois linhas (filas) e três colunas
S1 = Mul[:2, :3]
S1

array([[12,  8,  4],
       [ 5,  4,  3]])

In [42]:
# exemplo numpy-39
# todas linhas, as outras colunas ***
S2 = Mul[:3, ::2]
S2

array([[12,  4],
       [ 5,  3],
       [ 3,  2]])

In [43]:
# exemplo numpy-40
# submatriz reversa
R1 = Mul[::-1, ::-1]
R1

array([[ 1,  2,  3,  3],
       [ 2,  3,  4,  5],
       [ 0,  4,  8, 12]])

In [44]:
# exemplo numpy-41
# 1a coluna da matriz Mul
print(Mul[:,0])

[12  5  3]


In [45]:
# exemplo numpy-42
# submatriz 2x2
print(Mul)
sub_M = Mul[:2, :2]
sub_M

[[12  8  4  0]
 [ 5  4  3  2]
 [ 3  3  2  1]]


array([[12,  8],
       [ 5,  4]])

In [46]:
# exemplo numpy-43
# Modificar elementos da submatriz
sub_M[0,0]= -9
print(sub_M)
# modifica elemento da matriz
print(Mul)

[[-9  8]
 [ 5  4]]
[[-9  8  4  0]
 [ 5  4  3  2]
 [ 3  3  2  1]]


### Redimensionamento de Matrizes

In [47]:
# exemplo numpy-44
# redimensionar uma matriz
G = np.arange(1,10)
print('G =',G)
print(' ')
RS = G.reshape((3,3))
print('G = ',RS)

G = [1 2 3 4 5 6 7 8 9]
 
G =  [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Concatenação e Divisão de Matrizes

In [48]:
# exemplo numpy-45
# concatenação
A = np.array([3, 2, 1])
B = np.array([1, 0, -1])
C = np.concatenate([A,B])
C

array([ 3,  2,  1,  1,  0, -1])

In [49]:
# exemplo numpy-46
# + Concatenação 
Z = np.array([-9, -9, -9])
z = np.concatenate([A, B, Z])
z

array([ 3,  2,  1,  1,  0, -1, -9, -9, -9])

In [50]:
# exemplo numpy-47
# split = corte = fatia
xx = [1, 2, 3, 99, 99, 3, 2, 1]
xa, xb, xc = np.split(xx,[3, 5])
print(xa, xb, xc)

[1 2 3] [99 99] [3 2 1]


## Funções NumPy

### Expoentes e Logaritmos

In [51]:
# exemplo numpy-48
# expoentes
V = [1, 2, 3]
print("V =", V)
print("e^V =", np.exp(V))
print("2^V =", np.exp2(V))
print("3^V =", np.power(3, V))

V = [1, 2, 3]
e^V = [ 2.71828183  7.3890561  20.08553692]
2^V = [2. 4. 8.]
3^V = [ 3  9 27]


In [52]:
# exemplo numpy-49
# logaritmos
l = [1, 2, 4, 10]
print("l =", l)
print("ln(l) =", np.log(l))
print("log2(l) =", np.log2(l))
print("log10(l) =", np.log10(l))

l = [1, 2, 4, 10]
ln(l) = [0.         0.69314718 1.38629436 2.30258509]
log2(l) = [0.         1.         2.         3.32192809]
log10(l) = [0.         0.30103    0.60205999 1.        ]


In [53]:
# exemplo numpy-50
# funções especializadas
y = [0, 0.001, 0.01, 0.1]
print("exp(y) - 1 =", np.expm1(y))
print("log(1 + y) =", np.log1p(y))

exp(y) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + y) = [0.         0.0009995  0.00995033 0.09531018]


## Agregações: Min e Max

In [54]:
# exemplo numpy-51
#  Soma de todos os valores
L = np.random.random(100)
S = sum(L)
S

49.39628180998353

In [55]:
# exemplo numpy-52
#  tempo de compilação
big_matriz = np.random.rand(1000000)
%timeit sum(big_matriz)
%timeit np.sum(big_matriz)

312 ms ± 88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.37 ms ± 197 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [56]:
# exemplo numpy-53
# mínimo e máximo
min(big_matriz), max(big_matriz)

(7.74663314495605e-07, 0.9999985792356085)

In [57]:
# exemplo numpy-54
# mínimo e máximo
np.min(big_matriz), np.max(big_matriz)

(7.74663314495605e-07, 0.9999985792356085)

In [58]:
# exemplo numpy-55
# mínimo e máximo
%timeit min(big_matriz)
%timeit np.min(big_matriz)

169 ms ± 7.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
840 µs ± 35.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Funções de Agregação

| Função  |  NaN Versão| Descrição  | 
|:---     |:----------|:-----------|
|  np.sum | np.nansum | Compute sum of elements |
| np.prod | np.nanprod | Compute product of elements |
| np.mean | np.nanmean | Compute median of elements |
| np.std | np.nanstd | Compute standard deviation |
| np.var | np.nanvar | Compute variance |
| np.min | np.nanmin | Find minimum value |
| np.max | np.nanmax | Find maximum value |
| np.argmin | np.nanargmin | Find index of minimum value |
| np.argmax | np.nanargmax | Find index of maximum value |
| np.median | np.nanmedian | Compute median of elements |
| np.percentile | np.nanpercentile | Compute rank-based statistics of elements |
| np.any | N/A | Evaluate whether any elements are true |
| np.all | N/A | Evaluate whether all elements are true |


In [59]:
# exemplo numpy-56
# criando um vetor
vet = np.arange(1,100)
vet

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [60]:
# exemplo numpy-57
# Alguns agragados
vs = vet.sum()
vm = vet.mean()
vd = vet.std()
vmin = vet.min()
vmax = vet.max()
print('soma = ',vs)
print('Média = ',vm)
print('Desvio = ',vd)
print('Mínimo = ',vmin)
print('Máximo = ',vmax)
print('Mediana = ',np.median(vet))

soma =  4950
Média =  50.0
Desvio =  28.577380332470412
Mínimo =  1
Máximo =  99
Mediana =  50.0


**Exercício**: Os pesos (kg) dos alunos de curso são: 50, 55.5, 60.5, 60.8, 63.7, 68.9, 70.3, 80.5, 90. Usando essa informação fazer os cálculos para todas as funções de agregação.

In [61]:
# exemplo numpy-58
# Exemplo de uso de agregados
pesos = np.linspace(50, 80, num=50)
print(pesos)
valores = np.linspace(1, 30, num=50)
print(valores)
# * / -= / += / *=
print(pesos * valores) 

[50.         50.6122449  51.2244898  51.83673469 52.44897959 53.06122449
 53.67346939 54.28571429 54.89795918 55.51020408 56.12244898 56.73469388
 57.34693878 57.95918367 58.57142857 59.18367347 59.79591837 60.40816327
 61.02040816 61.63265306 62.24489796 62.85714286 63.46938776 64.08163265
 64.69387755 65.30612245 65.91836735 66.53061224 67.14285714 67.75510204
 68.36734694 68.97959184 69.59183673 70.20408163 70.81632653 71.42857143
 72.04081633 72.65306122 73.26530612 73.87755102 74.48979592 75.10204082
 75.71428571 76.32653061 76.93877551 77.55102041 78.16326531 78.7755102
 79.3877551  80.        ]
[ 1.          1.59183673  2.18367347  2.7755102   3.36734694  3.95918367
  4.55102041  5.14285714  5.73469388  6.32653061  6.91836735  7.51020408
  8.10204082  8.69387755  9.28571429  9.87755102 10.46938776 11.06122449
 11.65306122 12.24489796 12.83673469 13.42857143 14.02040816 14.6122449
 15.20408163 15.79591837 16.3877551  16.97959184 17.57142857 18.16326531
 18.75510204 19.34693878 19

In [62]:
# exemplo numpy-59
#  uso de -=
pesos -= valores
print(pesos)

[49.         49.02040816 49.04081633 49.06122449 49.08163265 49.10204082
 49.12244898 49.14285714 49.16326531 49.18367347 49.20408163 49.2244898
 49.24489796 49.26530612 49.28571429 49.30612245 49.32653061 49.34693878
 49.36734694 49.3877551  49.40816327 49.42857143 49.44897959 49.46938776
 49.48979592 49.51020408 49.53061224 49.55102041 49.57142857 49.59183673
 49.6122449  49.63265306 49.65306122 49.67346939 49.69387755 49.71428571
 49.73469388 49.75510204 49.7755102  49.79591837 49.81632653 49.83673469
 49.85714286 49.87755102 49.89795918 49.91836735 49.93877551 49.95918367
 49.97959184 50.        ]


In [63]:
# exemplo numpy-60
# soma = +
nova = pesos + valores
print(nova)

[50.         50.6122449  51.2244898  51.83673469 52.44897959 53.06122449
 53.67346939 54.28571429 54.89795918 55.51020408 56.12244898 56.73469388
 57.34693878 57.95918367 58.57142857 59.18367347 59.79591837 60.40816327
 61.02040816 61.63265306 62.24489796 62.85714286 63.46938776 64.08163265
 64.69387755 65.30612245 65.91836735 66.53061224 67.14285714 67.75510204
 68.36734694 68.97959184 69.59183673 70.20408163 70.81632653 71.42857143
 72.04081633 72.65306122 73.26530612 73.87755102 74.48979592 75.10204082
 75.71428571 76.32653061 76.93877551 77.55102041 78.16326531 78.7755102
 79.3877551  80.        ]


### Matrizes Multidimensionais

In [64]:
# exemplo numpy-61
# definição de uma função
def f(x,y):
    return x*y*10

In [65]:
# exemplo numpy-62
# informação pasada por tuplas separados por comas
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[  0,   0,   0,   0],
       [  0,  10,  20,  30],
       [  0,  20,  40,  60],
       [  0,  30,  60,  90],
       [  0,  40,  80, 120]])

In [66]:
# exemplo numpy-63
# chamar diretamente a função
c = f(3,3)
c

90

In [67]:
# exemplo numpy-64
# Mostra os elementos da linha 0 ao 4 da coluna 1
b[0:4,1]

array([ 0, 10, 20, 30])

In [68]:
# exemplo numpy-65
# acessando linhas de uma matriz
for fila in b:
    print(fila)

[0 0 0 0]
[ 0 10 20 30]
[ 0 20 40 60]
[ 0 30 60 90]
[  0  40  80 120]


### Funções

In [69]:
# exemplo numpy-66
# definição de uma função
def nome_f(parametro_a,parametro_b):
    # corpo da função
    soma = parametro_a + parametro_b
    return soma

In [70]:
# exemplo numpy-67
# chamando uma função
variavel = nome_f(9,9)
print('Variável = ',variavel)

Variável =  18


In [71]:
# exemplo numpy-68
# definir a função raiz quadrada
def RQ(n):
    v = np.sqrt(n)
    return v

In [72]:
# exemplo numpy-69
# chamando a função RQ
rq = RQ(4)
rq

2.0

In [73]:
# exemplo numpy-70
# definição da função signo
def sign(x):
    if x > 0:
        return 'Positivo'
    elif x < 0:
        return 'Negativo'
    else:
        return 'Nulo'

In [74]:
# exemplo numpy-71
# chamando a função sign
for x in [-1, 0, 1]:
    print('Sinal: ',sign(x))

Sinal:  Negativo
Sinal:  Nulo
Sinal:  Positivo


------
Marcelo Lisboa &copy; 2021. mlisboa@uft.edu.br